language: node_js
node_js:
  - 8
  
deploy:
  provider: npm
  email: github@cicoria.com
  api_key:
    secure: lefiMm68spOfA1YPXJLUlnp4cP75Wx2ShtG7kKXC6/nIwRHnUqG1YBaCM16MlmJdMCNAuXmiDq6MHFFIWypRU9OYyPweXL/IVo0tAms11InYMcW5dAmGA/U0yOmPO9pURt5etXHhav/J4uwo4M1RftxmeE4qKJiaIbJw4OsBpehoiDG5LB5VvLRucK4pkCRs5lcYHGsausAU58EWBrQeeEjMXmvXKjPaZWSJ5kCMaiBCmPVrx/Wjkkoyv17cDDgX1WtNZD02ilw7jrPs/QdzR+CEyKGofBLWOW2Jmz4848FSvcAzxL8ls3oRcxsTvQQbIVzHuhN3sTOChU3g2X3RsXPbmR6LVASEKx3cWhbGMh0IxTHtVVsbhYIFfDaXccfTwPIEatiR4pe8mzt/g7PlsDL51C8yecfR0OA6gktEBcd9/PUix3nOfit6YvnRijlcxp/bXzDtAmSoU9TH/IB8bxyjUcouVG57FN7FMKfPqbMu6WgC/f2CXPHfhF6TtCaATByV9t5cb/oEBFvtf5WSztLj13UfQ7Ju5Kwu/6WRpIz3TQWrxa6JAuRMO8s3tGlrkktXNccH7tGJ/gH9HwPX3ssoX9ZUlal5VwVW4cFEh/JcSQC7gKbTEtlcxjeH2wp9Qzc9mjpgd27pF5+Zyhn98ZpSDM1MpwEp4pApVYKlXmA=
  on:
    repo: cicorias/foobar-travis
